name: EBI Self Hosted tests


on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  test_ebi:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Check that there are tests that need running
      run: |
        git switch _gh_workflow_ebi_tests
        export GIT_DIFF_LAST_TESTS=$(git --no-pager diff --name-only main)
        echo "GIT_DIFF_LAST_TESTS=${GIT_DIFF_LAST_TESTS}"
        export GIT_DIFF_LAST_TESTS=$(expr "$GIT_DIFF_LAST_TESTS" == "" )
        echo "GIT_DIFF_LAST_TESTS=${GIT_DIFF_LAST_TESTS}"
        echo "GIT_DIFF_LAST_TESTS=$GIT_DIFF_LAST_TESTS" >> $GITHUB_ENV
    - name: Rebase main
      if: ${{ env.GIT_DIFF_LAST_TESTS == 0 }}
      run: git rebase main
    - name: Create python venv # Python is loaded by the job launcher sbatch script: `module load python/3.12.9`
      if: ${{ env.GIT_DIFF_LAST_TESTS == 0 }}
      run: |
        python -m venv --clear .venv
        .venv/bin/python --version
    - name: Install
      if: ${{ env.GIT_DIFF_LAST_TESTS == 0 }}
      run: |
        .venv/bin/pip install --upgrade pip
        .venv/bin/pip install '.[training]'
    - name: Run ebi tests
      if: ${{ env.GIT_DIFF_LAST_TESTS == 0 }}
      run: .venv/bin/python -m unittest discover -v -s ./tests_ebi -p '*test.py'
    - name: Push changes
      if: ${{ env.GIT_DIFF_LAST_TESTS == 0 }}
      run: git push
